import { type TArtistFormPersonalField } from "./types";

export const artistPersonalFields: TArtistFormPersonalField[] = [
  {
    title: "Фамилия",
    name: "identity_data.last_name",
    placeholder: "Иванов",
    type: "text",
    required: true,
    disabled: false,
    row: 1,
    column: 1,
  },
  {
    title: "Имя",
    name: "identity_data.first_name",
    placeholder: "Иван",
    type: "text",
    required: true,
    disabled: false,
    row: 1,
    column: 2,
  },
  {
    title: "Отчество",
    name: "identity_data.middle_name",
    placeholder: "Иванович",
    type: "text",
    required: false,
    disabled: false,
    row: 2,
    column: 1,
  },
  {
    title: "Дата рождения",
    name: "identity_data.birth_date",
    placeholder: "дд.мм.гггг",
    type: "date",
    required: true,
    disabled: false,
    row: 2,
    column: 2,
  },
  {
    title: "Адрес регистрации",
    name: "identity_data.registration_address",
    placeholder: "Москва",
    type: "text",
    required: true,
    disabled: false,
    row: 3,
    column: 1,
  },
  {
    title: "Email",
    name: "legal_profile.email",
    placeholder: "email@email.ru",
    type: "string",
    required: true,
    disabled: false,
    row: 4,
    column: 1,
  },
  {
    title: "Телефон",
    name: "legal_profile.phone",
    placeholder: "+7(___)___-__-__",
    type: "tel",
    required: true,
    disabled: false,
    row: 4,
    column: 2,
  },
];

export const artistPasportFields: TArtistFormPersonalField[] = [
  {
    title: "Паспорт серия",
    name: "identity_data.passport_series",
    placeholder: "1111",
    type: "text",
    required: true,
    disabled: false,
    row: 1,
    column: 1,
    maxLength: 4,
    minLength: 4,
  },
  {
    title: "Паспорт номер",
    name: "identity_data.passport_number",
    placeholder: "111111",
    type: "text",
    required: true,
    disabled: false,
    row: 1,
    column: 2,
    maxLength: 6,
    minLength: 6,
  },
  {
    title: "Код подразделения",
    name: "identity_data.passport_issued_by",
    placeholder: "111-111",
    type: "text",
    required: true,
    disabled: false,
    row: 2,
    column: 1,
    maxLength: 7,
    minLength: 7,
  },
  {
    title: "Дата выдачи паспорта",
    name: "identity_data.passport_issue_date",
    placeholder: "дд.мм.гггг",
    type: "date",
    required: true,
    disabled: false,
    row: 2,
    column: 2,
  },
];

export const artistIndividualPaymentFields: TArtistFormPersonalField[] = [
  {
    title: "ИНН",
    name: "identity_data.inn",
    placeholder: "000123456789",
    type: "text",
    required: true,
    disabled: false,
    row: 2,
    column: 2,
    maxLength: 12,
    minLength: 12,
  },
  {
    title: "Название банка",
    name: "bank_data.bank_name",
    placeholder: "Название банка",
    type: "text",
    required: true,
    disabled: false,
    row: 1,
    column: 2,
  },
  {
    title: "БИК",
    name: "bank_data.bik",
    placeholder: "123456789",
    type: "text",
    required: true,
    disabled: false,
    row: 1,
    column: 1,
    maxLength: 9,
    minLength: 9,
  },
  {
    title: "Корреспондентский счет",
    name: "bank_data.correspondent_account",
    placeholder: "30100000000000000000",
    type: "text",
    required: true,
    disabled: false,
    row: 2,
    column: 1,
    maxLength: 20,
    minLength: 20,
  },
  {
    title: "Расчетный счет",
    name: "bank_data.checking_account",
    placeholder: "00000000000000000000",
    type: "text",
    required: true,
    disabled: false,
    row: 3,
    column: 1,
    maxLength: 20,
    minLength: 20,
  },
  {
    title: "Организационная форма",
    name: "legal_profile.recipient_type",
    placeholder: "ИП / СМЗ",
    type: "text",
    required: true,
    disabled: false,
    row: 3,
    column: 2,
    options: [
      {
        label: "ИП",
        value: "individual_entrepreneur",
      },
      { label: "СМЗ", value: "self_employed" },
    ],
  },
];

export const artistEntityPaymentFields: TArtistFormPersonalField[] = [
  {
    title: "Название организации",
    name: "company_data.company_name",
    placeholder: "Название организации",
    type: "text",
    required: true,
    disabled: false,
    row: 1,
    column: 1,
    maxLength: 100,
    minLength: 2,
  },
  {
    title: "ОГРН",
    name: "company_data.ogrn",
    placeholder: "0000123456789",
    type: "text",
    required: true,
    disabled: false,
    row: 2,
    column: 1,
    maxLength: 13,
    minLength: 13,
  },
  {
    title: "ИНН",
    name: "company_data.inn",
    placeholder: "0123456789",
    type: "text",
    required: true,
    disabled: false,
    row: 2,
    column: 2,
    maxLength: 10,
    minLength: 10,
  },
  {
    title: "Юридический адрес",
    name: "company_data.company_address",
    placeholder: "Юридический адрес организации",
    type: "text",
    required: true,
    disabled: false,
    row: 3,
    column: 1,
    maxLength: 150,
    minLength: 2,
  },
  {
    title: "БИК",
    name: "bank_data.bik",
    placeholder: "123456789",
    type: "text",
    required: true,
    disabled: false,
    row: 4,
    column: 1,
    maxLength: 9,
    minLength: 9,
  },
  {
    title: "Название банка",
    name: "bank_data.bank_name",
    placeholder: "Название банка",
    type: "text",
    required: true,
    disabled: false,
    row: 4,
    column: 2,
  },
  {
    title: "Корреспондентский счет",
    name: "bank_data.correspondent_account",
    placeholder: "30100000000000000000",
    type: "text",
    required: true,
    disabled: false,
    row: 5,
    column: 1,
    maxLength: 20,
    minLength: 20,
  },
  {
    title: "Расчетный счет",
    name: "bank_data.checking_account",
    placeholder: "00000000000000000000",
    type: "text",
    required: true,
    disabled: false,
    row: 5,
    column: 2,
    maxLength: 20,
    minLength: 20,
  },
];


