import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Footer from "@/widgets/layout/ui/Footer/Footer";
import AppHeader from "./AppHeader";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const featureMono = localFont({
  src: [
    {
      path: "./fonts/FeatureMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/FeatureMono-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/FeatureMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-feature-mono",
  display: "swap",
});
const betterVcr = localFont({
  src: [
    {
      path: "./fonts/BetterVCR.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-better-vcr",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${featureMono.variable} ${betterVcr.variable}`}
      >
        <div className="app-shell">
          <div className="app-container">
            <AppHeader />
          </div>
          <main className="app-main">
            <div className="app-container">{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
